[project]
name = "pdfdownloadtool"
version = "0.1.1"
description = "Power up your crews with pdfdownloadtool"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.201.1",
    "requests>=2.31.0",
    "PyPDF2>=3.0.0"
]

[tool.crewai]
type = "tool"
